# Generated by Django 5.1.4 on 2025-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='No iniciado', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('create_ad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
